name: bing_wallpaper_example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  flutter_hooks: ^0.14.0
  hooks_riverpod: ^0.11.1
  google_fonts: ^2.2.0
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  bing_wallpaper:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
